apiVersion: v1
kind: Pod
metadata:
  name: app-deployment-v2
  labels:
    app: java
spec:
  containers: 
  - name: java
    image: azujal/blog-docker-versioning:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"